// Static fallback keyword list, used only before the live duckdb_keywords()
// dictionary loads (or when no agent is connected). DuckDB ≈ PostgreSQL plus a
// few DuckDB-specific extras (QUALIFY, EXCLUDE, REPLACE, PIVOT, …).
export const FALLBACK_KEYWORDS: string[] = [
  "SELECT",
  "FROM",
  "WHERE",
  "GROUP BY",
  "HAVING",
  "ORDER BY",
  "LIMIT",
  "OFFSET",
  "DISTINCT",
  "AS",
  "JOIN",
  "INNER JOIN",
  "LEFT JOIN",
  "RIGHT JOIN",
  "FULL JOIN",
  "CROSS JOIN",
  "ON",
  "USING",
  "WITH",
  "UNION",
  "UNION ALL",
  "INTERSECT",
  "EXCEPT",
  "INSERT INTO",
  "VALUES",
  "UPDATE",
  "SET",
  "DELETE",
  "CREATE TABLE",
  "CREATE SCHEMA",
  "CREATE VIEW",
  "CREATE OR REPLACE",
  "DROP TABLE",
  "DROP SCHEMA",
  "DROP VIEW",
  "ALTER TABLE",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "AND",
  "OR",
  "NOT",
  "IN",
  "BETWEEN",
  "LIKE",
  "ILIKE",
  "IS NULL",
  "IS NOT NULL",
  "ASC",
  "DESC",
  "NULLS FIRST",
  "NULLS LAST",
  "CAST",
  "EXISTS",
  "QUALIFY",
  "EXCLUDE",
  "REPLACE",
  "PIVOT",
  "UNPIVOT",
  "USING SAMPLE",
  "RETURNING",
];

// The keywords that can legally start a statement. DuckDB's own
// duckdb_keywords() doesn't categorize words by statement position, so this
// stays a curated, hand-maintained list rather than something derived live.
export const STATEMENT_START_KEYWORDS: string[] = [
  "SELECT",
  "WITH",
  "INSERT INTO",
  "UPDATE",
  "DELETE",
  "CREATE TABLE",
  "CREATE SCHEMA",
  "CREATE VIEW",
  "DROP TABLE",
  "ALTER TABLE",
  "EXPLAIN",
  "ATTACH",
  "DETACH",
  "USE",
  "CALL",
  "PRAGMA",
  "SET",
  "COPY",
  "VACUUM",
  "CHECKPOINT",
  "EXPORT DATABASE",
  "IMPORT DATABASE",
  "SUMMARIZE",
  "DESCRIBE",
  "SHOW",
  "LOAD",
  "INSTALL",
  "BEGIN",
  "COMMIT",
  "ROLLBACK",
];
